import Head from "next/head";
import styles from "@/styles/pages/home.module.scss";
import Image from "next/image";
import Headphones from "@/components/Headphones";

const imagePanels = [
  { src: "/img/tracks-cover.jpg", alt: "panel1", label: "tracks" },
  { src: "/img/artists-cover.jpg", alt: "panel2", label: "artists" },
  { src: "/img/genres-cover.jpg", alt: "panel3", label: "genres" },
  {
    src: "/img/taste-profile-cover.jpg",
    alt: "panel4",
    label: "taste profile",
  },
];

export default function Home() {
  return (
    <>
      <Head>
        <title>Blendify | Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.page}>
        <div className={styles.panels}>
          {imagePanels.map((panel, index) => (
            <div key={index} className={styles.panel}>
              <Image
                src={panel.src}
                alt={panel.alt}
                fill
                sizes="(max-width: 1200px) 20vw"
              />
              <div className={styles.panel__label}>{panel.label}</div>
            </div>
          ))}
        </div>
        <div className={styles.blendify}>
          <h1 className={styles.blendify__title}>blendify</h1>
          <div className={styles.blendify__desc}>
            A personalized summary of your unique taste in music
          </div>
        </div>
        <div className={styles.headphones}>
          <Headphones />
        </div>
      </main>
    </>
  );
}
