import React from "react";
import Head from "next/head";
import routes from "@/routes";
import styles from "@/styles/components/page.module.scss";
import { useRouter } from "next/router";
import { getSession } from "next-auth/react";
import Link from "next/link";

interface PageProps {
  children: React.ReactNode;
  transition?: "enter" | "exit";
}

export default function Page({ children }: PageProps) {
  const router = useRouter();
  const { pathname } = router;

  const currentRoute = routes[pathname] || "";

  return (
    <>
      <Head>
        <title>{String(`Blendify | ${currentRoute}`)}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.page}>{children}</main>
    </>
  );
}

export async function getServerSideProps() {
  const session = await getSession();

  if (!session) {
    return {
      redirect: {
        destination: "/login",
        permanent: true,
      },
    };
  }

  return {
    props: {
      session,
    },
  };
}
