import React from "react";
import Head from "next/head";
import styles from "@/styles/components/page.module.scss";
import { usePathname } from "next/navigation";
import { routes } from "@/routes";
import { motion } from "framer-motion";
import { getSession } from "next-auth/react";

interface PageProps {
  children: React.ReactNode;
}

export default function Page({ children }: PageProps) {
  const pathname = usePathname();
  const currentRoute = routes.find((route) => route.path === pathname);

  return (
    <>
      <Head>
        <title>{`Blendify | ${currentRoute?.name || ""}`}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <motion.main
        className={styles.page}
        transition={{ duration: 0.7, ease: [0.4, 0, 0.2, 1] }}
      >
        {children}
      </motion.main>
    </>
  );
}

export async function getServerSideProps() {
  const session = await getSession();

  if (!session) {
    return {
      redirect: {
        destination: "/login",
        permanent: true,
      },
    };
  }

  return {
    props: {
      session,
    },
  };
}
